openapi: 3.0.0
info:
  title: IP API Microservice
  description: Microservice to fetch IP information using IPAPI.
  version: 1.0.0
paths:
  /:
    get:
      summary: Get IP Information
      responses:
        '200':
          description: A JSON object with IP information.
