name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push IP_MICROSERVICIO
        uses: docker/build-push-action@v2
        with:
          context: ./IP_MICROSERVICIO
          file: ./IP_MICROSERVICIO/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ip_microservicio:latest

      - name: Build and push MICROSERVICIO_REPUTACION_IP
        uses: docker/build-push-action@v2
        with:
          context: ./MICROSERVICIO_REPUTACION_IP
          file: ./MICROSERVICIO_REPUTACION_IP/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservicio_reputacion_ip:latest

      - name: Build and push MICROSERVICIO_URL
        uses: docker/build-push-action@v2
        with:
          context: ./MICROSERVICIO_URL
          file: ./MICROSERVICIO_URL/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservicio_url:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  
          script: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/ip_microservicio:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/microservicio_reputacion_ip:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/microservicio_url:latest
            docker stop ip_microservicio || true
            docker stop microservicio_reputacion_ip || true
            docker stop microservicio_url || true
            docker rm ip_microservicio || true
            docker rm microservicio_reputacion_ip || true
            docker rm microservicio_url || true
            docker run -d --name ip_microservicio -p 2001:2001 ${{ secrets.DOCKER_USERNAME }}/ip_microservicio:latest
            docker run -d --name microservicio_reputacion_ip -p 2002:2002 ${{ secrets.DOCKER_USERNAME }}/microservicio_reputacion_ip:latest
            docker run -d --name microservicio_url -p 2004:2004 ${{ secrets.DOCKER_USERNAME }}/microservicio_url:latest
